### ISSUE TITLE
Device parameter issue

### ISSUE THREAD

**Issue by shootyzee** [raphaelquast/beatstep#62]
Hi, thanks for your great work on this, its just what I've been looking for since getting a Beatstep. I am using the most up to date midi script (1.8)

I am finding that when the beatstep is first connected to ableton the encoders (1-4 and 9-12) work the device parameters in ableton as expected in the initial layer, but if change to another layer e.g. the shift layer or control layer, then return to the initial layer, the encoders no longer function in either the initial layer or in the shift layer. They seem to work fine for manipulating the device parameters in the control layer and when the shift layer is used from the control layer.

**Comment by raphaelquast** [comment]
hey, 
thanks... and thanks for reporting!

...you are right, the device-controls are not properly re-activated if no layer is active.
It will be fixed shortly 😄

**Comment by raphaelquast** [comment]
that was a quick one 😄 
it's fixed (alongside another pending issue) in **BeatStep_Q v1.8.1** !   (released just now)
