### ISSUE TITLE
Doesn't show up in Ableton 11

### ISSUE THREAD

**Issue by Carvite** [raphaelquast/beatstep#83]
Hi, sorry to bring up such a fundamental question, but I installed it in the appropriate directory ( I think) X:\ProgramData\Ableton\Live 11 Suite\Resources\MIDI Remote Scripts\beatstep-2.0
When I open Abletone>Options>Preferences  Beatstep Q is not in the MIDI devices list.
I'm using Ableton Live 11.3.3, and Windows 11.
Thank you for your time!

**Comment by raphaelquast** [comment]
Hey, directory looks right... try renaming the directory to `Beatstep_Q`, that might help.

**Comment by Carvite** [comment]
Yup, that was it ... thx a lot, I'll start playing with your script!

**Comment by raphaelquast** [comment]
Great, have fun! 😄 
(I'll close this issue since its resolved... feel free to open a new one if you run into any other troubles!)
